"""
notebook_exporter.py — Generate a Colab/Jupyter-ready .ipynb notebook
that reproduces every cleaning and feature-engineering step chosen in DataMind.
"""
from __future__ import annotations

import json
import textwrap
from datetime import datetime
from typing import Optional


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _code_cell(source: "str | list[str]") -> dict:
    """Create a code cell JSON object."""
    if isinstance(source, list):
        source_lines = source
    else:
        source_lines = source.splitlines(keepends=True)
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source_lines,
    }


def _markdown_cell(source: "str | list[str]") -> dict:
    """Create a markdown cell JSON object."""
    if isinstance(source, list):
        source_lines = source
    else:
        source_lines = source.splitlines(keepends=True)
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source_lines,
    }


def _safe(col: str) -> str:
    """Convert a column name to a Python-safe variable-name suffix."""
    return "".join(c if c.isalnum() else "_" for c in col).strip("_")


# ─── Main generator ───────────────────────────────────────────────────────────

def generate_notebook(
    filename: str,
    cleaning_config: dict,
    engineering_config: dict,
    adv_config: dict,
    col_types: dict,
    target_col: Optional[str],
    cleaning_changelog: list,
    engineering_changelog: list,
) -> str:
    """
    Build a complete .ipynb notebook JSON string that mirrors all cleaning
    and feature-engineering choices made in the DataMind UI.

    Returns the notebook as a JSON string ready to be written to a .ipynb file.
    """
    cells = []
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    base_name = filename.rsplit(".", 1)[0] if "." in filename else filename

    # ── 0. Header ────────────────────────────────────────────────────────────
    cells.append(_markdown_cell(
        "# \U0001f9e0 DataMind \u2014 Auto-Generated Analysis Notebook\n"
        "\n"
        "**Dataset:** `" + filename + "`  \n"
        "**Generated:** " + ts + "  \n"
        "\n"
        "This notebook was automatically generated by **DataMind** and reproduces\n"
        "every cleaning and feature-engineering step you selected in the UI.\n"
        "\n"
        "> \u2705 Ready to run on **Google Colab**, **JupyterLab**, or any IDE that supports `.ipynb` files.\n"
    ))

    # ── 1. Install & Imports ─────────────────────────────────────────────────
    cells.append(_markdown_cell("## \U0001f4e6 1 \u00b7 Install Dependencies & Imports"))

    install_code = (
        "# Install required packages (uncomment if running on Colab / fresh environment)\n"
        "# !pip install pandas numpy scikit-learn openpyxl\n"
        "\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler, RobustScaler\n"
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n"
        "\n"
        "print('\u2705 All packages imported successfully')\n"
    )
    cells.append(_code_cell(install_code))

    # ── 2. Load Data ─────────────────────────────────────────────────────────
    cells.append(_markdown_cell("## \U0001f4c2 2 \u00b7 Load Your Dataset"))

    load_code = (
        "# \u2500\u2500 Option A: Upload from your local machine (Google Colab) \u2500\u2500\u2500\u2500\u2500\u2500\n"
        "# from google.colab import files\n"
        "# uploaded = files.upload()\n"
        "# import io\n"
        "# df = pd.read_csv(io.BytesIO(uploaded['" + filename + "']))\n"
        "\n"
        "# \u2500\u2500 Option B: Load from file path (local Jupyter / IDE) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
        "df = pd.read_csv('" + filename + "')  # Change path/extension as needed\n"
        "\n"
        "print(f'\u2705 Dataset loaded: {df.shape[0]:,} rows \u00d7 {df.shape[1]} columns')\n"
        "df.head()\n"
    )
    cells.append(_code_cell(load_code))

    # Quick info
    cells.append(_code_cell(
        "# Quick overview\n"
        "print('Shape:', df.shape)\n"
        "print('\\nColumn types:')\n"
        "print(df.dtypes)\n"
        "print('\\nMissing values:')\n"
        "print(df.isnull().sum())\n"
    ))

    # ── 3. Data Cleaning ─────────────────────────────────────────────────────
    cells.append(_markdown_cell(
        "## \U0001f9f9 3 \u00b7 Data Cleaning\n"
        "\n"
        "All steps below mirror the choices made in the DataMind **Clean** tab.\n"
    ))

    cleaning_lines = [
        "df_clean = df.copy()\n",
        "\n",
    ]

    # 3a. Remove duplicates
    if cleaning_config.get("remove_duplicates", False):
        cleaning_lines += [
            "# \u2500\u2500 Remove duplicate rows \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
            "n_before = len(df_clean)\n",
            "df_clean = df_clean.drop_duplicates().reset_index(drop=True)\n",
            "print(f'Duplicates removed: {n_before - len(df_clean):,} rows')\n",
            "\n",
        ]

    # 3b. Per-column rules
    columns_cfg = cleaning_config.get("columns", {})
    for col, col_cfg in columns_cfg.items():
        null_strat = col_cfg.get("null_strategy", "none")
        out_strat = col_cfg.get("outlier_strategy", "keep")

        if null_strat == "none" and out_strat == "keep":
            continue

        safe = _safe(col)
        cleaning_lines.append("# \u2500\u2500 Column: '" + col + "' \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n")

        # Null handling
        if null_strat not in ("none",):
            if null_strat == "mean":
                cleaning_lines += [
                    "fill_val_" + safe + " = df_clean['" + col + "'].mean()\n",
                    "df_clean['" + col + "'] = df_clean['" + col + "'].fillna(fill_val_" + safe + ")\n",
                    "print(f'[" + col + "] Nulls filled with mean: {fill_val_" + safe + ":.4f}')\n",
                ]
            elif null_strat == "median":
                cleaning_lines += [
                    "fill_val_" + safe + " = df_clean['" + col + "'].median()\n",
                    "df_clean['" + col + "'] = df_clean['" + col + "'].fillna(fill_val_" + safe + ")\n",
                    "print(f'[" + col + "] Nulls filled with median: {fill_val_" + safe + ":.4f}')\n",
                ]
            elif null_strat == "mode":
                cleaning_lines += [
                    "fill_val_" + safe + " = df_clean['" + col + "'].mode()[0]\n",
                    "df_clean['" + col + "'] = df_clean['" + col + "'].fillna(fill_val_" + safe + ")\n",
                    "print(f'[" + col + "] Nulls filled with mode: {fill_val_" + safe + "}')\n",
                ]
            elif null_strat == "ffill":
                cleaning_lines += [
                    "df_clean['" + col + "'] = df_clean['" + col + "'].ffill()\n",
                    "print('[" + col + "] Nulls forward-filled')\n",
                ]
            elif null_strat == "bfill":
                cleaning_lines += [
                    "df_clean['" + col + "'] = df_clean['" + col + "'].bfill()\n",
                    "print('[" + col + "] Nulls backward-filled')\n",
                ]
            elif null_strat == "zero":
                cleaning_lines += [
                    "df_clean['" + col + "'] = df_clean['" + col + "'].fillna(0)\n",
                    "print('[" + col + "] Nulls filled with 0')\n",
                ]
            elif null_strat == "drop":
                cleaning_lines += [
                    "n_before = len(df_clean)\n",
                    "df_clean = df_clean.dropna(subset=['" + col + "']).reset_index(drop=True)\n",
                    "print(f'[" + col + "] Dropped rows with nulls: {n_before - len(df_clean):,}')\n",
                ]
            elif null_strat == "custom":
                custom_val = col_cfg.get("custom_value", 0)
                cleaning_lines += [
                    "df_clean['" + col + "'] = df_clean['" + col + "'].fillna(" + repr(custom_val) + ")\n",
                    "print('[" + col + "] Nulls filled with custom value: " + repr(custom_val) + "')\n",
                ]

        # Outlier handling
        if out_strat in ("cap", "remove"):
            cleaning_lines += [
                "# Outlier handling for '" + col + "' (IQR method)\n",
                "q1_" + safe + " = df_clean['" + col + "'].dropna().quantile(0.25)\n",
                "q3_" + safe + " = df_clean['" + col + "'].dropna().quantile(0.75)\n",
                "iqr_" + safe + " = q3_" + safe + " - q1_" + safe + "\n",
                "lower_" + safe + " = q1_" + safe + " - 1.5 * iqr_" + safe + "\n",
                "upper_" + safe + " = q3_" + safe + " + 1.5 * iqr_" + safe + "\n",
            ]
            if out_strat == "cap":
                cleaning_lines += [
                    "df_clean['" + col + "'] = df_clean['" + col + "'].clip(lower=lower_" + safe + ", upper=upper_" + safe + ")\n",
                    "print(f'[" + col + "] Outliers capped to [{lower_" + safe + ":.3f}, {upper_" + safe + ":.3f}]')\n",
                ]
            elif out_strat == "remove":
                cleaning_lines += [
                    "outlier_mask_" + safe + " = (df_clean['" + col + "'] < lower_" + safe + ") | (df_clean['" + col + "'] > upper_" + safe + ")\n",
                    "n_before = len(df_clean)\n",
                    "df_clean = df_clean[~outlier_mask_" + safe + "].reset_index(drop=True)\n",
                    "print(f'[" + col + "] Outlier rows removed: {n_before - len(df_clean):,}')\n",
                ]

        cleaning_lines.append("\n")

    cleaning_lines += [
        "print(f'\\n\u2705 Cleaning complete: {df_clean.shape[0]:,} rows \u00d7 {df_clean.shape[1]} columns')\n",
        "print(f'   Missing values remaining: {df_clean.isnull().sum().sum():,}')\n",
        "df_clean.head()\n",
    ]

    cells.append(_code_cell(cleaning_lines))

    # ── 4. Feature Engineering ───────────────────────────────────────────────
    cells.append(_markdown_cell(
        "## \u2699\ufe0f 4 \u00b7 Feature Engineering\n"
        "\n"
        "Mirrors the choices made in the DataMind **Feature Engineer** tab.\n"
    ))

    eng_lines = [
        "df_eng = df_clean.copy()\n",
        "\n",
    ]

    # 4a. Datetime decomposition
    dt_cfg = engineering_config.get("datetime", {})
    if dt_cfg:
        eng_lines.append("# \u2500\u2500 Datetime Decomposition \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n")
        for col, feats in dt_cfg.items():
            if not feats:
                continue
            safe = _safe(col)
            eng_lines.append("dt_" + safe + " = pd.to_datetime(df_eng['" + col + "'], infer_datetime_format=True)\n")
            for feat in feats:
                eng_lines.append("df_eng['" + col + "_" + feat + "'] = dt_" + safe + ".dt." + feat + "\n")
            eng_lines += [
                "df_eng = df_eng.drop(columns=['" + col + "'])\n",
                "print('\u2705 Datetime decomposed: " + col + " \u2192 " + str(feats) + "')\n",
                "\n",
            ]

    # 4b. Categorical encoding
    enc_cfg = engineering_config.get("encoding", {})
    if enc_cfg:
        eng_lines.append("# \u2500\u2500 Categorical Encoding \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n")
        for col, method in enc_cfg.items():
            if method == "none":
                continue
            safe = _safe(col)
            if method == "label":
                eng_lines += [
                    "le_" + safe + " = LabelEncoder()\n",
                    "df_eng['" + col + "'] = le_" + safe + ".fit_transform(df_eng['" + col + "'].astype(str).fillna('__MISSING__'))\n",
                    "print(f'\u2705 Label encoded: " + col + " \u2192 {len(le_" + safe + ".classes_)} classes')\n",
                ]
            elif method == "onehot":
                eng_lines += [
                    "df_eng = pd.get_dummies(df_eng, columns=['" + col + "'], prefix='" + col + "', drop_first=False, dtype=int)\n",
                    "print('\u2705 One-hot encoded: " + col + "')\n",
                ]
            elif method == "ordinal":
                eng_lines += [
                    "cats_" + safe + " = sorted(df_eng['" + col + "'].dropna().astype(str).unique())\n",
                    "ord_map_" + safe + " = {cat: idx for idx, cat in enumerate(cats_" + safe + ")}\n",
                    "df_eng['" + col + "'] = df_eng['" + col + "'].astype(str).map(ord_map_" + safe + ")\n",
                    "print(f'\u2705 Ordinal encoded: " + col + " \u2192 {len(cats_" + safe + ")} levels')\n",
                ]
            eng_lines.append("\n")

    # 4c. Scaling
    scale_cfg = engineering_config.get("scaling", {})
    if scale_cfg:
        eng_lines.append("# \u2500\u2500 Feature Scaling \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n")
        for col, method in scale_cfg.items():
            if method == "none":
                continue
            safe = _safe(col)
            if method == "standard":
                eng_lines += [
                    "scaler_" + safe + " = StandardScaler()\n",
                    "df_eng[['" + col + "']] = scaler_" + safe + ".fit_transform(df_eng[['" + col + "']].astype(float))\n",
                    "print('\u2705 Standard scaled: " + col + "')\n",
                ]
            elif method == "minmax":
                eng_lines += [
                    "scaler_" + safe + " = MinMaxScaler()\n",
                    "df_eng[['" + col + "']] = scaler_" + safe + ".fit_transform(df_eng[['" + col + "']].astype(float))\n",
                    "print('\u2705 MinMax scaled: " + col + "')\n",
                ]
            elif method == "robust":
                eng_lines += [
                    "scaler_" + safe + " = RobustScaler()\n",
                    "df_eng[['" + col + "']] = scaler_" + safe + ".fit_transform(df_eng[['" + col + "']].astype(float))\n",
                    "print('\u2705 Robust scaled: " + col + "')\n",
                ]
            eng_lines.append("\n")

    # ── 5. Advanced Transforms ───────────────────────────────────────────────
    adv_section_needed = any([
        adv_config.get("drop_cols"),
        adv_config.get("log_transform"),
        adv_config.get("sqrt_transform"),
        adv_config.get("square_transform"),
        adv_config.get("interaction_terms"),
        adv_config.get("custom_formulas"),
        adv_config.get("binning"),
    ])

    if adv_section_needed:
        eng_lines.append("# \u2500\u2500 Advanced / Power Transforms \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n")

        for col in adv_config.get("drop_cols", []):
            eng_lines += [
                "df_eng = df_eng.drop(columns=['" + col + "'], errors='ignore')\n",
                "print('\u2705 Dropped column: " + col + "')\n",
            ]

        for col in adv_config.get("log_transform", []):
            safe = _safe(col)
            eng_lines += [
                "# Log1p transform for '" + col + "'\n",
                "_min_" + safe + " = df_eng['" + col + "'].min()\n",
                "_offset_" + safe + " = max(0.0, -_min_" + safe + " + 1e-6) if _min_" + safe + " <= 0 else 0.0\n",
                "df_eng['" + col + "_log'] = np.log1p(df_eng['" + col + "'] + _offset_" + safe + ")\n",
                "print(f'\u2705 Log1p transform: " + col + " \u2192 " + col + "_log')\n",
                "\n",
            ]

        for col in adv_config.get("sqrt_transform", []):
            safe = _safe(col)
            eng_lines += [
                "# Sqrt transform for '" + col + "'\n",
                "_min_" + safe + " = df_eng['" + col + "'].min()\n",
                "_offset_" + safe + " = max(0.0, -_min_" + safe + ") if _min_" + safe + " < 0 else 0.0\n",
                "df_eng['" + col + "_sqrt'] = np.sqrt(df_eng['" + col + "'] + _offset_" + safe + ")\n",
                "print(f'\u2705 Sqrt transform: " + col + " \u2192 " + col + "_sqrt')\n",
                "\n",
            ]

        for col in adv_config.get("square_transform", []):
            eng_lines += [
                "df_eng['" + col + "_sq'] = df_eng['" + col + "'] ** 2\n",
                "print('\u2705 Squared: " + col + " \u2192 " + col + "_sq')\n",
            ]

        for pair in adv_config.get("interaction_terms", []):
            if len(pair) == 2:
                a, b = pair
                new_col = a + "_x_" + b
                eng_lines += [
                    "df_eng['" + new_col + "'] = df_eng['" + a + "'] * df_eng['" + b + "']\n",
                    "print('\u2705 Interaction term: " + new_col + "')\n",
                ]

        for item in adv_config.get("custom_formulas", []):
            name = item.get("name", "").strip()
            expr = item.get("formula", "").strip()
            if name and expr:
                eng_lines += [
                    "# Custom formula: " + name + " = " + expr + "\n",
                    "try:\n",
                    "    df_eng['" + name + "'] = df_eng.eval('" + expr + "')\n",
                    "    print('\u2705 Formula column created: " + name + "')\n",
                    "except Exception as e:\n",
                    "    print(f'\u26a0\ufe0f Formula failed for " + name + ": {e}')\n",
                ]

        for item in adv_config.get("binning", []):
            col = item.get("col", "")
            bins = int(item.get("bins", 5))
            strategy = item.get("strategy", "quantile")
            if col:
                new_col = col + "_binned"
                if strategy == "quantile":
                    eng_lines += [
                        "df_eng['" + new_col + "'] = pd.qcut(df_eng['" + col + "'], q=" + str(bins) + ", labels=False, duplicates='drop').astype(str)\n",
                        "print('\u2705 Quantile binned: " + col + " \u2192 " + new_col + " (" + str(bins) + " bins)')\n",
                    ]
                else:
                    eng_lines += [
                        "df_eng['" + new_col + "'] = pd.cut(df_eng['" + col + "'], bins=" + str(bins) + ", labels=False).astype(str)\n",
                        "print('\u2705 Uniform binned: " + col + " \u2192 " + new_col + " (" + str(bins) + " bins)')\n",
                    ]

    eng_lines += [
        "\n",
        "print(f'\\n\u2705 Feature engineering complete: {df_eng.shape[0]:,} rows \u00d7 {df_eng.shape[1]} columns')\n",
        "df_eng.head()\n",
    ]

    cells.append(_code_cell(eng_lines))

    # ── 5. Final Dataset Summary ─────────────────────────────────────────────
    cells.append(_markdown_cell("## \U0001f4ca 5 \u00b7 Final Dataset Summary"))

    summary_code = (
        "print('=== Final Dataset Info ===')\n"
        "print(f'Shape: {df_eng.shape}')\n"
        "print(f'Missing values: {df_eng.isnull().sum().sum()}')\n"
        "print()\n"
        "print('Column types:')\n"
        "print(df_eng.dtypes)\n"
        "print()\n"
        "df_eng.describe()\n"
    )
    cells.append(_code_cell(summary_code))

    # ── 6. Save Output ───────────────────────────────────────────────────────
    cells.append(_markdown_cell("## \U0001f4be 6 \u00b7 Save the Processed Dataset"))

    save_code = (
        "# Save to CSV\n"
        "output_path = 'datamind_" + base_name + "_processed.csv'\n"
        "df_eng.to_csv(output_path, index=False)\n"
        "print(f'\u2705 Saved to: {output_path}')\n"
        "\n"
        "# Optional: save to Excel\n"
        "# df_eng.to_excel('datamind_" + base_name + "_processed.xlsx', index=False)\n"
        "\n"
        "# Optional: download in Google Colab\n"
        "# from google.colab import files\n"
        "# files.download('datamind_" + base_name + "_processed.csv')\n"
    )
    cells.append(_code_cell(save_code))

    # ── 7. Optional: Target column / model ready section ─────────────────────
    if target_col:
        cells.append(_markdown_cell(
            "## \U0001f3af 7 \u00b7 Ready for Modeling\n"
            "\n"
            "Your **target column** is `" + target_col + "`.  \n"
            "Below is a quick starter snippet to split your data for training.\n"
        ))
        split_code = (
            "from sklearn.model_selection import train_test_split\n"
            "\n"
            "# Separate features and target\n"
            "X = df_eng.drop(columns=['" + target_col + "'], errors='ignore')\n"
            "y = df_eng['" + target_col + "']\n"
            "\n"
            "# Train / Test split (80/20)\n"
            "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n"
            "\n"
            "print(f'Training set:  {X_train.shape[0]:,} rows')\n"
            "print(f'Test set:      {X_test.shape[0]:,} rows')\n"
            "print(f'Features:      {X_train.shape[1]}')\n"
            "print(f'Target:        " + target_col + "')\n"
        )
        cells.append(_code_cell(split_code))
    else:
        cells.append(_markdown_cell(
            "## \U0001f3af 7 \u00b7 Ready for Modeling\n"
            "\n"
            "No target column was selected.  \n"
            "Select `X` (features) and `y` (target) from `df_eng` to start training your model.\n"
        ))

    # ── Changelog as markdown ─────────────────────────────────────────────────
    if cleaning_changelog or engineering_changelog:
        log_md = "## \U0001f4dd Appendix \u00b7 DataMind Pipeline Log\n\n"
        if cleaning_changelog:
            log_md += "### \U0001f9f9 Cleaning Steps\n"
            for entry in cleaning_changelog:
                clean_entry = entry.replace("**", "")
                log_md += "- " + clean_entry + "\n"
            log_md += "\n"
        if engineering_changelog:
            log_md += "### \u2699\ufe0f Feature Engineering Steps\n"
            for entry in engineering_changelog:
                clean_entry = entry.replace("**", "")
                log_md += "- " + clean_entry + "\n"
        cells.append(_markdown_cell(log_md))

    # ── Assemble notebook ─────────────────────────────────────────────────────
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.9.0",
            },
            "colab": {
                "provenance": [],
                "name": "datamind_" + base_name + "_analysis.ipynb",
            },
        },
        "cells": cells,
    }

    return json.dumps(notebook, indent=2, ensure_ascii=False)
